
/*table  t_hq_m_member*/
--update--
CREATE TRIGGER upd_hq_m_member ON t_hq_m_member
FOR update AS  IF NOT (UPDATE(int_basedata) OR UPDATE(dt_lastupdatetime))
  BEGIN
    INSERT INTO tmp_hq_m_member
    (
		log_type,

		vch_memberno,
		vch_member,
		ch_typeno,
		vch_id,
		dt_birthday,
		vch_tel,
		vch_handtel,
		vch_address,
		dt_limit,
		ch_state,
		num_limit,
		ch_cardflag,
		vch_cardno,
		vch_password,
		vch_operID,
		dt_operdate,
		dt_lastupdatetime,
		int_basedata,
		dt_sendtime,
		ch_send_branchno,
		ch_upflag,
		vch_sex,
		bth_flag,
		dt_build,
		/* old record*/
		vch_member2,
		ch_typeno2,
		vch_id2,
		dt_birthday2,
		vch_tel2,
		vch_handtel2,
		vch_address2,
		dt_limit2,
		ch_state2,
		num_limit2,
		ch_cardflag2,
		vch_cardno2,
		vch_password2,
		vch_operID2,
		dt_operdate2,
		dt_lastupdatetime2,
		int_basedata2,
		dt_sendtime2,
		ch_send_branchno2,
		ch_upflag2,
		vch_sex2,
		bth_flag2,
		dt_build2,
	
		add_source,
		add_main)
         SELECT 'UPD', 
			ins.vch_memberno,
			ins.vch_member,
			ins.ch_typeno,
			ins.vch_id,
			ins.dt_birthday,
			ins.vch_tel,
			ins.vch_handtel,
			ins.vch_address,
			ins.dt_limit,
			ins.ch_state,
			ins.num_limit,
			ins.ch_cardflag,
			ins.vch_cardno,
			ins.vch_password,
			ins.vch_operID,
			ins.dt_operdate,
			ins.dt_lastupdatetime,
			ins.int_basedata,
			ins.dt_sendtime,
			ins.ch_send_branchno,
			ins.ch_upflag,
			ins.vch_sex,
			ins.bth_flag,
			ins.dt_build,
			
			del.vch_member,
			del.ch_typeno,
			del.vch_id,
			del.dt_birthday,
			del.vch_tel,
			del.vch_handtel,
			del.vch_address,
			del.dt_limit,
			del.ch_state,
			del.num_limit,
			del.ch_cardflag,
			del.vch_cardno,
			del.vch_password,
			del.vch_operID,
			del.dt_operdate,
			del.dt_lastupdatetime,
			del.int_basedata,
			del.dt_sendtime,
			del.ch_send_branchno,
			del.ch_upflag,
			del.vch_sex,
			del.bth_flag,
			del.dt_build,
			'1','0'
         FROM inserted ins,deleted del
   END

